
### 📄 GET ALL USERS
GET https://express-js-login.onrender.com/api/users
Authorization: Bearer mocked.token.123456
Content-Type: application/json

### 🔐 LOGIN
POST https://express-js-login.onrender.com/api/auth/login
Content-Type: application/json

{
  "email": "admin@example.com",
  "password": "123456"
}

### 📝 REGISTER
POST https://express-js-login.onrender.com/api/auth/register
Content-Type: application/json

{
  "email": "newuser@example.com",
  "password": "mypass123"
}

### ❌ DELETE USER BY ID
DELETE https://express-js-login.onrender.com/api/users/1
Authorization: Bearer mocked.token.123456
Content-Type: application/json
